SET NAMES utf8;


CREATE TABLE IF NOT EXISTS `itu-ajax` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`login` VARCHAR(8) COLLATE utf8_unicode_ci NOT NULL,
	`cnt` LONGTEXT COLLATE utf8_unicode_ci NOT NULL,
	`dts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8
	COLLATE = utf8_unicode_ci;
